name: TimeCommander
main: com.haniokasai.nukkit.TimeCommander.Main
version: 1.0.0
author: haniokasai
api: ["1.0.0"]
description: TimeCommander https://forums.pocketmine.net/plugins/timecommander.768/
website: http://haniokasai.com
